version: "2.4"

services:
  hue-play:
    build:
      context: $ROOT_PROJECT
      dockerfile: docker/Dockerfile
    command: run-forever python play.py -sgr -v
    restart: always
    volumes:
      - "${ROOT_VOLUME_PATH}:/app/hue-play"
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    init: true
